# Generated by Django 3.2.9 on 2022-12-07 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loan',
            new_name='LendLease',
        ),
    ]
