# Generated by Django 3.2.9 on 2022-12-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('country', models.CharField(max_length=30, verbose_name='Pais')),
                ('passport', models.CharField(max_length=30, verbose_name='Pasaporte')),
                ('age', models.PositiveIntegerField()),
                ('appellative', models.CharField(max_length=10, verbose_name='Apelativo')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'db_table': 'person',
            },
        ),
    ]
